
spring:
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094,localhost:9095
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000 
    admin:
      properties:
        [bootstrap.servers]: 'localhost:9092, localhost:9093, localhost:9094, localhost:9095'